os: linux
dist: xenial
language: erlang
script: "make all"

otp_release:
   - 22.3
   - 22.0
   - 21.3
   - 21.0
   - 20.3
   - 20.0
   - 19.3

# coverage tests
jobs:
  include:
    - language: erlang
      otp_release: 22.3
      before_script:
            - >
                printf "\n{cover_enabled, true}.\n{cover_export_enabled, true}.
                \n{cover_excl_modules, [
                proper_array,
                proper_dict,
                proper_gb_sets,
                proper_gb_trees,
                proper_orddict,
                proper_ordsets,
                proper_prop_remover,
                proper_queue,
                proper_sets,
                proper_transformer,
                proper_unused_imports_remover,
                vararg]}." >> rebar.config
      after_success:
            - git clone https://github.com/covertool/covertool.git
            - cd covertool && make compile && cd ..
            - find _build/ -name *.coverdata 
            - find _build/test/cover/ -name *.coverdata -exec ./covertool/covertool -cover {} -output {}.coverage.xml \;
            - mv _build/test/cover/*.xml .
            - rm -rf covertool/
            - bash <(curl -s https://codecov.io/bash)

cache:
   directories:
   - .plt
