os: linux
dist: xenial
language: erlang
script: "make all"

otp_release:
   - 22.3
   - 19.3

# coverage tests
jobs:
  include:
    - language: erlang
      otp_release: 22.3
      env: COVER=true
      after_success:
        - for f in _build/test/covertool/*.xml; do cp "$f" $(basename "${f%.xml}.coverage.xml"); done
        - bash <(curl -s https://codecov.io/bash)

cache:
   directories:
   - .plt
